### ISSUE TITLE
Use kseq for parsing FASTA

### ISSUE THREAD

**Issue by GordonHoklinder** [OndrejSladky/kmercamel#16]
From @karel-brinda :
> If possible, I would recommend using the following inline library:
> https://github.com/attractivechaos/klib/blob/master/kseq.h
> It's super well-optimized, well-debugged, and used by many other bioinformatics C/C++ programs. We used it previously eg inProphAsm.
> Importantly, it implicitly supports gzip as input (no additional treatment necessary).
> Here's an example how to use it: https://github.com/attractivechaos/klib/blob/master/test/kseq_test.c

**Comment by OndrejSladky** [comment]
#38 implements this for Local, LocalAC and GlobalAC
