### ISSUE TITLE
Suboptimal C++ string handling degrades the performance of Ahomaton-based algs

### ISSUE THREAD

**Issue by karel-brinda** [OndrejSladky/kmercamel#35]
It seems to me that the GreedyAC alg somehow became much slower than before.

In the current version, I'm getting
```
$ time kmercamel/kmers -k 15  -p <(xzcat spneumoniae.fa.xz) -a greedyAC > /dev/null

real	0m36.825s
user	0m9.733s
sys	0m21.072s
```

If I use canonical k-mers (the `-c` option, it becomes even worse
```
$ time kmercamel/kmers -c -k 15  -p <(xzcat spneumoniae.fa.xz) -a greedyAC > /dev/null

real	9m23.860s
user	0m29.113s
sys	2m14.312s
```

At least the non-canonical version used to be much faster (eg with k-mers @ fda2f7e), see 
https://github.com/karel-brinda/superstring-kmers-paper/blob/ed981bf861c6ab7efe020ca5b49d5d4507d0dd7f/experiments/05_kmer_camel_comparison_v1/results/immortalite.time.tsv#L159

**Comment by karel-brinda** [comment]
Copying here the additional info from our last emails the AC performance degradation:

## How it looks like in htop

![image](https://user-images.githubusercontent.com/8779046/216679740-86c000ce-6f45-4ab3-acb5-bfe55ec7d3b2.png)

## Examples of lines that might be causing this

Zkusil jsem novou verzi a vypadá to, že problém trvá. Kouknul jsem se do zdrojáků a mám pár příkladů míst, kde bych tipoval, že to bude strašně zápasit s přesuny v paměti:

Velice časté rozšiřování napravo (možná lepší by byl seznam a spojit to na konec):
https://github.com/GordonHoklinder/kmercamel/blob/f3f36f1e989d25e808696893b0a7d20b3fc6b62e/generalized_simplitigs_ac.h#L121

Trochu tady:
https://github.com/GordonHoklinder/kmercamel/blob/f3f36f1e989d25e808696893b0a7d20b3fc6b62e/generalized_simplitigs_ac.h#L100

Tady si myslím, že to může být skoro kritické:
https://github.com/GordonHoklinder/kmercamel/blob/f3f36f1e989d25e808696893b0a7d20b3fc6b62e/generalized_simplitigs_ac.h#L114
Obávám se, že tady se musí při každém rozšíření napravo dělat skoro neuvěřitelné alokace & přesuny – v podstatě se při každém rozšíření i o jedno písmenko podle mě kopíruje celý pseudosimplitig.

**Comment by OndrejSladky** [comment]
This should already be solved via #38 .
