### ISSUE TITLE
Optimizing the number of runs approximately without running the ILP

### ISSUE THREAD

**Issue by PavelVesely** [OndrejSladky/kmercamel#66]
For very large datasets (e.g., the human genome), solving the ILP to minize the number of runs of 1s may be too time or memory consuming. I suggest to provide a heuristic version that only runs `HeuristicPreSolve` and then sets `1`s in all other intervals, on which we now apply the ILP. We can call it `runsapprox` or something like that

**Comment by OndrejSladky** [comment]
Good idea. Depending on how large the ILP is we could also provide some standard approx. alg. for Set Cover like greedy/primal-dual alg. But if the ILP is small, this is probably not relevant.

**Comment by OndrejSladky** [comment]
If we find, we want the approx ilp solver, we can reopen this issue.

**Comment by PavelVesely** [comment]
I think it's not worth trying to implement a good approximation algorithm for set cover, at least not now. In the end, it may require more resources than a good ILP solver on the data that we have now.
(Actually, we tried just glpk and not something better, right?)
